/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nlctxkyythejpghcpubi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sY3R4a3l5dGhlanBnaGNwdWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MjMxMDMsImV4cCI6MjA5MTE5OTEwM30.KK3y77QuX4PbIZaA_MC-HUMczsT56L_AY73PEnjR-Pg"